name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install environment
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda upgrade conda
        $CONDA/bin/conda create -n awesomeness_environment python
        $CONDA/bin/conda install -n awesomeness_environment --file requirements.txt
    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install -n awesomeness_environment flake8
        $CONDA/bin/conda run -n awesomeness_environment flake8 ./awesomeness ./tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        $CONDA/bin/conda install -n awesomeness_environment flake8
        $CONDA/bin/conda run -n awesomeness_environment pytest ./tests
